### PR TITLE
Add more options

### PR DESCRIPTION
**Pull request by nurdism**
this pr adds 4 new options to the cli 

--no-relations: Do not include relations
--optional-relations: Make relations optional types
--no-hidden: Do not include hidden model attributes
--timestamp-strings: Output timestamps as strings

### CODE REVIEW

**Comment by nurdism** [comment]
this fixes #31 without breaking changes and addresses #32 as well

**Comment by acidjazz** [comment]
Thanks for the pr! reviewing shortly

**Comment by acidjazz** [comment]
@tcampbPPU what do you think about the TS date type expecting an object vs a Laravel endpoint response always coming back as a json - do we keep it an option to go text? or make the switch making it an option to make it a date?

**Comment by nurdism** [comment]
added another option `--optional-nullables: Output nullable attributes as optional fields`

**Comment by tcampbPPU** [comment]
yea I think union type works fine from @nurdism suggestion

**Comment by acidjazz** [comment]
@nurdism if you can please:

* default dates to string since Date is wrong either way
* make the option --timestamp-dates for people that use this and convert the response themselves
* add a small section to the readme showing these options - it can be between Requiresments and Custom Interfaces - it can easily be a dump of ./artisan model:typer --help

**Comment by nurdism** [comment]
@acidjazz updated the requested changes

**Pull request merged**
